### ISSUE TITLE
RMC message is parsed without a timezone

### ISSUE THREAD

**Issue by npahucki** [Knio/pynmea2#100]
Per the spec: https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_RMC.html the date time in the RMC message is UTC, however, pynmea2 parses it and creates a date time with no timezone, thus calling timestamp() on the returned date returns the wrong timestamp. 

To reproduce:
```
msg = '$GPRMC,184446.000,A,3720.18653,N,12153.38874,W,0.0,0.0,130220,,,A*7E'
parsed = pynmea2.parse(msg)
assert parsed.datetime.timestamp()  == 1581619486.0
```

The above assertion fails unless your computer is set to UTC timezone. 

The workaround to the bug for anyone else bumping against this is to `replace` the datetime with one that has the proper timezone: 
```
msg = '$GPRMC,184446.000,A,3720.18653,N,12153.38874,W,0.0,0.0,130220,,,A*7E'
parsed = pynmea2.parse(msg)
assert parsed.datetime.replace(tzinfo=timezone.utc).timestamp()  == 1581619486.0
```

**Comment by barbacbd** [comment]
@Knio I opened a PR for this one already. If you had a different idea about how to handle it you can close the PR but it seemed simple enough so I did it a little while ago.
