### ISSUE TITLE
SKU:TEL0137 Gps Module Empty Data

### ISSUE THREAD

**Issue by ugurgunes95** [Knio/pynmea2#141]
I have a gps module which is SKU:TEL0137. When i've tried to receive gps data from the module, i can't see the longitude and latitude data. The data that i see is almost empty. I'm going to leave a screenshot about the data i can read. How to fix it? Thanks for help.

![the result that i see](https://user-images.githubusercontent.com/54820657/177784134-54f68d29-0773-496b-858c-de084566d929.png)

**Comment by barbacbd** [comment]
Are the messages above coming from the gps module or is this after printing the results of parsing with the pynmea module?

Can you confirm that you are getting full NMEA 0183 streams from the gps module?

**Comment by ugurgunes95** [comment]
Thoose messages are coming from the gps module without parsing. Yes, I can confirm that.

**Comment by ugurgunes95** [comment]
I guess GPS module was not working correctly, so I've decided to change it.
