### ISSUE TITLE
support the FLARM protocol by adding $PFLAA and $PFLAU traffic sentences  

### ISSUE THREAD

**Issue by nrbray** [Knio/pynmea2#150]
Request for this feature, available in pull request https://github.com/Knio/pynmea2/pull/149

**Comment by kamiccolo** [comment]
I suppose, it can be closed, due to https://github.com/Knio/pynmea2/pull/154 getting merged already ;)

**Comment by nrbray** [comment]
> I suppose, it can be closed, due to ~#154~ #149 getting merged already ;)

Thank you ;)
