### ISSUE TITLE
Attribute Errors

### ISSUE THREAD

**Issue by 17dshaikh** [Knio/pynmea2#159]
In python when I parse the message and I want the longitude, it says attribute error, I use msg.longitude

**Comment by Alperencode** [comment]
That message might not have the longitude attribute. I recommend looping through message fields and finding its attributes using `getattr()`.

Example:
```python
msg = pynmea2.parse(sentence)
dict = {}
for key in msg.fields:
    dict[key[0]] = getattr(msg, str(key[1]))
```
In this example `key[0]` is attribute like "longitude" and `key[1]` is its parsed value.

You can check my implementation for complete example:
- [Complete repository](https://github.com/Alperencode/NMEA-Parser)
- [Related code](https://github.com/Alperencode/NMEA-Parser/blob/dacf252ddc116caadbbd38aa3b7374fbbe783703/parsers/data_based_parser.py)
