### ISSUE TITLE
Needs porting to Python 3.12

### ISSUE THREAD

**Issue by stefanor** [Knio/pynmea2#163]
Python 3.12 dropped the `imp` module.

https://docs.python.org/3.12/whatsnew/3.12.html#imp

The code using `imp` should be ported to `importlib`

**Comment by dreirund** [comment]
> *@Knio closed this as [completed](https://github.com/Knio/pynmea2/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #164 on Feb 11*

Can you make a new release, including the fix, so that distributions that use releases and not latest git state can pick up easily?
