### ISSUE TITLE
Stream reader could defer raising exceptions to end of input buffer

### ISSUE THREAD

**Issue by liamw9534** [Knio/pynmea2#41]
Just a thought but you might want to consider allowing the stream reader to defer parsing exceptions rather than raising them immediately to the caller.  The problem with raising the exceptions immediately is that you then drop out and lose the remainder of the stream buffer even though it might contain legitimate data after an item that caused the parser to fail.

**Comment by Knio** [comment]
Added some basic error handling in 1.7.0
