### ISSUE TITLE
Garmin (and possibly other proprietary) sentences don't parse correctly

### ISSUE THREAD

**Issue by silentquasar** [Knio/pynmea2#44]
My Garmin GPSMAP 78s outputs the following proprietary sentences:
`$PGRME,27.5,M,46.0,M,53.6,M*1C`
`$PGRMZ,50,f,*1D`
`$PGRMM,WGS 84*06`

These are not correctly parsed by pynmea2 because it puts the sentence subtype ('E', 'Z', or 'M', respectively) as the first data item. Thus I get the following output for the above messages, respectively:
`<GRME(hpe='E', hpe_unit='27.5', vpe='M', vpe_unit='46.0', osepe='M', osepe_unit='53.6') data=['M']>`
`<GRMZ(altitude='Z', altitude_unit='50', pos_fix_dim='f') data=['']>`
`<GRMM(datum='M') data=['WGS 84']>`

**Comment by silentquasar** [comment]
Propose porting `__init__()` from ubx.py:
```python
    def __init__(self, manufacturer, data):
        self.sentence_type = manufacturer + data[1]
        super(GRM, self).__init__(manufacturer, data[2:])
```

**Comment by Knio** [comment]
Thanks!
