### ISSUE TITLE
[Enhancement] parsing data from multiple sentences into a single object

### ISSUE THREAD

**Issue by ajRiverav** [Knio/pynmea2#57]
Scenario: 
The user wishes to parse the entire file (that is, multiple sentences, same type), and have the data stored in a single object. After parsing the file and returning data to msg, one would get the, say, altitude data as:

```
>>>msg.altitude
( 100, 200, 300 ) 
```

msg.altitude returns a tuple

**Comment by Knio** [comment]
This doesn't really fit into the scope of a parser.

Looks like you just want [zip](https://docs.python.org/3/library/functions.html#zip)
