### ISSUE TITLE
Parsing multiple sentences together?

### ISSUE THREAD

**Issue by Tomvictor** [Knio/pynmea2#65]
Hey,

How can I parse multiple sentence? is that possible?
Eg:
I have the multiple sentences in a buffer, can I feed it directly to pynmea?
<code>
$GPRMC,041626.000,A,1009.9738,N,07618.6555,E,0.00,115.25,100517,,,A*6F$GPVTG,115.25,T,,M,0.00,N,0.00,K,A*3F$GPGGA,041626.000,1009.9738,N,07618.6555,E,1,6,1.24,10.6,M,-93.4,M,,*48$GPGSA,A,3,27,16,23,03,09,08,,,,,,,1.56,1.24,0.96*09$GPGSV,4,1,13,23,58,007,23,03,52,210,21,08,48,131,18,27,37,081,16*71$GPGSV,4,2,13,22,34,178,,09,30,335,25,16,23,029,30,07,22,308,*7E$GPGSV,4,3,13,11,19,171,,28,11,223,,01,11,186,,30,02,278,*78$GPGSV,4,4,13,193,,,*40$GLGSV,3,1,10,70,65,312,,69,49,167,,73,32,312,16,80,22,006,*6C$GLGSV,3,2,10,83,18,136,,71,15,331,,82,15,083,,74,08,258,*61$GLGSV,3,3,10,68,01,157,,84,01,185,*69$GPGLL,1009.9738,N,07618.6555,E,041626.000,A,A*58$GPTXT,01,01,02,ANTSTATUS=OPEN*2B
</code>

**Comment by Knio** [comment]
See these examples:
* https://github.com/Knio/pynmea2#streaming and
* https://github.com/Knio/pynmea2/blob/master/examples/serial.py#L6
