### ISSUE TITLE
In NMEAStreamReader: decode stream data to make it work in Python3

### ISSUE THREAD

**Issue by TishSerg** [Knio/pynmea2#72]
When using Python 3 it gives following error:
```
File "C:\Python33\lib\site-packages\pynmea2\stream.py", line 48, in next
lines = (self.buffer + data).split('\n')
TypeError: Can't convert 'bytes' object to str implicitly
```

To fix it just replace in `stream.py` line 48:
`lines = (self.buffer + data).split('\n')` with 
`lines = (self.buffer + data.decode('ascii')).split('\n')`

**Comment by Knio** [comment]
Hi, I think the better solution for this is to set your encoding correctly in your underlying IO layer. pynmea is just supposed to be a data library where all inputs and outputs are strings, and can't assume any particular IO or devices.
